list: [
    "turn_300.txt", #0
    "turn_400.txt", #1
    "turn_500.txt", #2
    "turn_600.txt", #3
    "turn_700.txt", #4
  ]

profile_idx_size: 5
# idx = mode選択時
profile_idx: [
    {
      # 0: 探索パラメータindex&最短 300
      run_param: 0,
      normal: 0,
      large: 0,
      orval: 0,
      dia45: 0,
      dia45_2: 0,
      dia135: 0,
      dia135_2: 0,
      dia90: 0,
    },
    {
      # 1: 最短パラメータ 400
      run_param: 1,
      normal: 1,
      large: 1,
      orval: 1,
      dia45: 1,
      dia45_2: 1,
      dia135: 1,
      dia135_2: 1,
      dia90: 1,
    },
    {
      # 2: 最短パラメータ 500
      run_param: 2,
      normal: 0,
      large: 2,
      orval: 2,
      dia45: 2,
      dia45_2: 2,
      dia135: 2,
      dia135_2: 2,
      dia90: 2,
    },
    {
      # 3: 最短パラメータ 600
      run_param: 3,
      normal: 0,
      large: 3,
      orval: 3,
      dia45: 3,
      dia45_2: 3,
      dia135: 3,
      dia135_2: 3,
      dia90: 3,
    },
    {
      # 4: 最短パラメータ 700
      run_param: 4,
      normal: 0,
      large: 4,
      orval: 4,
      dia45: 4,
      dia45_2: 4,
      dia135: 4,
      dia135_2: 4,
      dia90: 4,
    },
  ]
